// boxdefines.h was generated by ProtoGen version 2.4.b

#ifndef _BOXDEFINES_H
#define _BOXDEFINES_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "ReverseGeocacheProtocol.h"

typedef struct
{
    unsigned centerText : 1; //!< Text is centered on the screen
}ClueOptionBits_t;

//! return the minimum encoded length for the ClueOptionBits_t structure
#define getMinLengthOfClueOptionBits_t() (1)

//! Encode a ClueOptionBits_t structure into a byte array
void encodeClueOptionBits_t(uint8_t* data, int* bytecount, const ClueOptionBits_t* user);

//! Decode a ClueOptionBits_t structure from a byte array
int decodeClueOptionBits_t(const uint8_t* data, int* bytecount, ClueOptionBits_t* user);

typedef struct
{
    float            lat;       //!< Location latitude
    float            lng;       //!< Location longitude
    uint16_t         threshold; //!< Distance threshold (m)
    ClueTypes        type;      //!< Clue type
    ClueOptionBits_t options;   //!< Extra clue options
}Waypoint_t;

//! return the minimum encoded length for the Waypoint_t structure
#define getMinLengthOfWaypoint_t() (12)

//! Encode a Waypoint_t structure into a byte array
void encodeWaypoint_t(uint8_t* data, int* bytecount, const Waypoint_t* user);

//! Decode a Waypoint_t structure from a byte array
int decodeWaypoint_t(const uint8_t* data, int* bytecount, Waypoint_t* user);

#ifdef __cplusplus
}
#endif
#endif
